name: foodie_scan
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2+1
  path: ^1.9.1
  openfoodfacts: ^3.30.2
  camera: ^0.12.0+1
  google_mlkit_barcode_scanning: ^0.14.2
  google_mlkit_text_recognition: ^0.15.1
  google_fonts: ^8.1.0
  flutter_local_notifications: ^22.0.0
  timezone: ^0.11.0
  flutter_timezone: ^5.1.0
  sqflite_common_ffi: ^2.4.0+3
  sqlite3_flutter_libs: ^0.6.0+eol

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/camara.png
    - assets/icons/app_icon.png
    - assets/icons/basura.png
    - assets/icons/categorias.png
    - assets/icons/despensa.png
    - assets/icons/history.png
    - assets/icons/home.png
    - assets/icons/tick.png
    - assets/icons/notFound.png

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#D9D689"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
